package com.agristorage.enums;

public enum DocumentType {
    RDB_CERTIFICATE,
    STORAGE_OWNERSHIP_PROOF,
    DRIVING_LICENSE,
    VEHICLE_REGISTRATION,
    NATIONAL_ID,
    FOOD_STORAGE_LICENSE,
    RSB_CERTIFICATION,
    VEHICLE_INSPECTION_CERTIFICATE,
    TRANSPORT_LICENSE,
    OTHER
}